### ISSUE TITLE
Write a product planning

### ISSUE THREAD

**Issue by RvdK** [MatthijsKok/TI2806-Contextproject#13]
Write a product planning according to the given format:

**Introduction**
**Product**

- High-level product backlog (set of epics aligned with the product vision)
- Roadmap (major release schedule, release goals)

**Product backlog (first version with estimates and prioritized user stories)**

- User stories of features
- User stories of defects (if applicable)
- User stories of technical improvements (if applicable)
- User stories of know-how acquisition
- Initial release plan (milestones, MRFs per release)

**Definition of Done (backlog items, sprints, releases)
Glossary**

**Comment by RvdK** [comment]
https://www.sharelatex.com/project/5906f1b5e0b90d35795a8fa6

**Comment by eriksennema** [comment]
subtasks
- [ ] #36 Introduction and Glossary 
- [ ] #28 High-level product backlog
- [ ] #29 Roadmap
- [ ] #30 User stories
- [ ] #34 Release plan
- [ ] #35 Definition of Done
